### ISSUE TITLE
Niche discussions about library development

### ISSUE THREAD

**Issue by JulianOrteil** [ponoor/python-step-series#3]
A variety of command tests fail only for the STEP800. These failures range everywhere from commands not being applied and timeouts (no response) to--depending on the speed of the tests--incorrect responses or the device reporting incorrect command parameters.

Note: This ticket only applies to the 0.0.2 branch.

**Incorrectly applied commands:**
`FAILED tests/step800/test_alarm_settings.py::TestAlarmSettings::test_over_current - assert 375.0 == 1875.0`
`FAILED tests/step800/test_alarm_settings.py::TestAlarmSettings::test_stall_report - assert 31.25 == 2187.5`
`FAILED tests/step800/test_home_limit_sensors_settings.py::TestHomeLimitSensorsSettings::test_home_sw_mode - assert False == 1`
`FAILED tests/step800/test_motor_driver_settings.py::TestMotorDriverSettings::test_microstep_mode - assert 0 == 5`
`FAILED tests/step800/test_motor_driver_settings.py::TestMotorDriverSettings::test_low_speed_optimize_threshold - AssertionError: assert False`
`FAILED tests/step800/test_motor_driver_settings.py::TestMotorDriverSettings::test_set_position_list_report_interval - assert False`
`FAILED tests/step800/test_position_management_settings.py::TestPositionManagementSettings::test_position - assert 0 == -99999`
`FAILED tests/step800/test_position_management_settings.py::TestPositionManagementSettings::test_el_pos - assert 0 == 2`
`FAILED tests/step800/test_position_management_settings.py::TestPositionManagementSettings::test_mark - 
assert 0 == 123456`

(Note the assertion tests are `returned_value == expected_value`)

**Timeouts:**
`FAILED tests/step800/test_position_management_settings.py::TestPositionManagementSettings::test_position_list - TimeoutError: timed-out waiting...`

Based on my testing, I do not see these as being bugs with the library. Are there prerequisites for the above commands that I am unaware of which is why they are failing, or is this something that needs to be addressed by a patch to the firmware?

CC @kanta

**Comment by kanta** [comment]
@JulianOrteil Thank you for the tests！
Do you know any example of succeeded commands?

**Comment by JulianOrteil** [comment]
@kanta Can you elaborate on what you mean by "succeeded commands"? Attempting to send the commands (like `/setOverCurrentThreshold`, `/setStallTheshold`, etc) whether through the tests or through the REPL results in them apparently not being applied.

I'll also be able to share the raw string commands tomorrow if you need them.

All other commands not listed above succeed. Please let me know if that answers your question :)

**Comment by kanta** [comment]
@JulianOrteil Sorry for my confusing expression, I wanted to know the results of other commands, now I know the rest of above are working. There are no difference for prerequisites between STEP400 and STEP800 so if these commands work for STEP400, then they should work with STEP800 as well. 
What is the response of `/getVersion` from your board?

**Comment by JulianOrteil** [comment]
@kanta

`Version(address='/version', firmware_name='STEP800_R1', firmware_version='1.0.2', compile_date='Dec 17 2021 08:28:48')`

**Comment by kanta** [comment]
@JulianOrteil Thanks, the firmware version seems good. Probably these problems are not from a single reason.

1. I found a bug in my code, the response of `/getLowSpeedOptimizeThreshold` was wrong. You can find a fixed firmware on [develop branch](https://github.com/ponoor/STEP800/tree/develop) of STEP800 repo. Thank you for pointing this out!
2. `/setElPos` and `/setMicrostepMode` should be sent during the driver is in HiZ state. Could you send `/hardHiZ` before those command to make sure of it?
3. Rest of them are mystery... These functionalities are working correctly in my environment (Cycling'74 Max on Win11). All command tests were succeeded with STEP400, correct?

**Comment by JulianOrteil** [comment]
@kanta Thanks for helping me out with this. I think most of these issues are because the motor I am using burned itself out and is causing some problems on its own. I've now switched the motor to an `SM-42BYG011-25` which is one of the "officially supported" that you have configurations for.

Let me re-evaluate my tests with this new motor and report back if the issues clear themselves up.

At any rate, running the tests *without* any motors connected on the STEP800 produces the above issues as well. To answer your question in 3, yes every command succeeds on the STEP400 (with or without motors attached).

**Comment by JulianOrteil** [comment]
@kanta I have found another issue. On the latest firmware for the STEP800, `/getThermalStatus` returns an out-of-bounds response according to [the docs](https://ponoor.com/en/docs/step-series/osc-command-reference/alarm-settings/#getthermalstatus_intmotorid): `ThermalStatus(address='/thermalStatus', motorID=1, >>>>> thermalStatus=6 <<<<<)`

The STEP400 does not have this issue.

Also, `/getLowSpeedOptimizeThreshold` is fixed, so thank you for doing that.

Otherwise, so far, most of these issues do appear to be caused by that bad motor. I'm rewriting tests to make them more effective and intuitive regardless, so any further issues should be better narrowed down.

Jules

**Comment by kanta** [comment]
@JulianOrteil You are right! My code was wrong and I fixed the problem. Please check the [develop branch](https://github.com/ponoor/STEP800/tree/develop). This was one of tiny differences between L6470 and PowerSTEP01, and I had completely overlooked it. Big thanks to your test program!

In STEP400 and STEP800, the power supply of the MCU and stepper drivers are independent. From the responses of incorrectly applied commands are 0(zero). Some of them are not zero but these value show the driver response was 0 value. These often occur when the MCU are working but stepper drivers are stopped. Are you connecting the USB port of your STEP800 to PC? A bigger motor (low impedance motor) can consume bigger current and sometimes cause the power supply shutdown. If you give the logic power via USB, the MCU is still survive but the responses from the drivers will be 0.

**Comment by JulianOrteil** [comment]
@kanta My pleasure. Just happy to help!

Anyways, I was running the old motor (it's unlabeled so I couldn't tell you exactly what it is) with a 0-52V, 10A variable power supply. I set it at 24-25V while connected to the board through the barrel plug (I now have it down at 12V with the new motor as it only needs 12V). Otherwise, all of these potential issues I am running into are being discovered by my tests of this library which is sending commands via Ethernet. I only connect the board to the PC when I need to load new firmware, otherwise, the USB-C port is left unplugged while I test.

Since these new tests are all currently succeeding (many of which are from the list above) when the board is powered through the barrel plug, I will run them again tomorrow but with the board powered via USB-only and see if they start failing again to verify your hypothesis.

Quick question though, is it safe to power the board via the USB and barrel plug? I know most Arduino devices (like the Mega) are safe against that, but I am just curious if both boards are as well.

Jules

**Comment by kanta** [comment]
@JulianOrteil I see, your power supply seems enough roomy for our tests.
It's no problem to power both the barrel plug and USB. I have always powered both during a developing process and never had a problem with it. 
NOTE: The barrel plug and the screw terminal are connected as parallel so we should not apply different voltages to each.

**Comment by JulianOrteil** [comment]
@kanta Got it, thanks.

Anyways, it does appear to be your hypothesis is correct. Powering the device through just USB, without a motor attached, is causing more tests to fail (i.e. `/getBusy` and `/getUvlo` both return 1 with no motor attached). I'm not yet finished with the other tests, but I'll share if anything else comes up.

Thanks again,
Jules

**Comment by JulianOrteil** [comment]
@kanta Another question, this time just to clarify `/enableElectromagnetBrake`, `/activate`, and `/free`.

- `/enableElectromagnetBrake 4 1` essentially sets a flag indicating EM-brake functionality is now permissible on motor 4.
- `/activate 4 0` acts as a manual EM-brake activation; the motor is disengaged and the EM-brake is engaged to hold the motor in position
- `/activate 4 1` does the opposite; the motor is engaged and the EM-brake is disengaged
- `/free 4 [state]` disengages both the motor and the brake; essentially "neutral"

(Btw, you're missing the `[state]` documentation in `/free` if that parameter is meant to be there)

Thanks,
Jules

**Comment by kanta** [comment]
@JulianOrteil Yes, your understanding is totally correct. And for `/free`, there is no `state`!
Wrong : `/free (int)motorID (bool)state`
Correct : `/free (int)motorID`

Thank you for your review! I will update the doc. So many mistakes actually...

**Comment by kanta** [comment]
The [doc](https://ponoor.com/en/docs/step-series/osc-command-reference/brake/) is updated. Sadly the link to `/free` is changed due to elimination of the argument...

**Comment by JulianOrteil** [comment]
@kanta I don't mean to insult you! 😅

I've actually been meaning to ask you about documentation. The library here will need to be documented which I'll obviously have to write, but would you also like me to review the English version of your current docs? I don't want to step on your toes any more than I have, so if you would prefer me not to, that is no issue.

Now, about where to host the documentation for this library. Nearly every Python library uses a site like ReadTheDocs (RTD). The cool thing about RTD is it will automatically compile documentation from code docstrings when you update them. This means that to update the docs about a code change, you just have to update the docstring and RTD will automatically compile a new version for you. But, because you already have all documentation about the Step-series on your website, I'll leave it up to you on where you'd like to host (I'd be against hosting it in 2 places).

**Comment by kanta** [comment]
@JulianOrteil This is an amazing offer to me! The documents are needed to review for English and also it's content. If you can help, that would be great!
So far the docs are maintained in this repo.
https://github.com/ponoor/step-series-support/tree/main/docs
There is not automatic update system so I manually upload them to the web server.

I haven't tried documents hosting services so let me check about it.
Thank you so much!

**Comment by JulianOrteil** [comment]
@kanta My pleasure! Like I said, if you would like to host the documentation on a site like RTD, then I would also recommend moving your current documentation there as well. This would mean I'd most likely transfer all of your current documentation into the docstrings of the dataclasses in `commands.py`.

Let me know what you think 😄

**Comment by kanta** [comment]
@JulianOrteil I've been doing some research on what RTD is all about. This could be big changes for the docs and bit complicated to me but I think it is a good opportunity to properly structure the whole documentation.
So basically I am positive to use RTD, but my understanding is quite limited so let me have some questions.

1. The current documents contain various information like a hardware setup or a tutorial, so I guess only the OSC command reference will be suitable for RTD, how do you think?
2. If the docs are embedded to python codes, should we edit the library code every time we want to update the document's text? Can we separate them to 2 repositories?
3. Shall we move to another place to discuss about the documentation things? Like [Discussions](https://github.com/ponoor/step-series-support/discussions).

Thanks!

**Comment by JulianOrteil** [comment]
> @JulianOrteil I've been doing some research on what RTD is all about. This could be big changes for the docs and bit complicated to me but I think it is a good opportunity to properly structure the whole documentation.
> So basically I am positive to use RTD, but my understanding is quite limited so let me have some questions.
> 
> 1. The current documents contain various information like a hardware setup or a tutorial, so I guess only the OSC command reference will be suitable for RTD, how do you think?
> 2. If the docs are embedded to python codes, should we edit the library code every time we want to update the document's text? Can we separate them to 2 repositories?
> 3. Shall we move to another place to discuss about the documentation things? Like [Discussions](https://github.com/ponoor/step-series-support/discussions).
> 
> Thanks!

@kanta My apologies. I completely failed to mention you can write normal documentation using the reStructuredText syntax. So, for example, the API reference (like your "OSC Commands Reference") will be embedded in the library code and automatically compiled from there. Tutorials, explanations, example code, etc will be written in the `docs` directory in this repo and then compiled from there. Both of these are then aggregated into a single build directory of html webpages for us to review before RTD displays them. Very efficient.

As an example, here's a [link](https://loguru.readthedocs.io/en/stable/) to the documentation for loguru, one of my favorite Python libraries.

But I agree, let's move this over to discussions. We have definitely exceeded the original purpose of this issue.

Jules

**Comment by JulianOrteil** [comment]
Okay, all STEP800 tests have been completed. I have not encountered any further issues regarding this ticket, so I will now close this as resolved.

**Comment by JulianOrteil** [comment]
Discussion of using RTD to host documentation has been moved to here: https://github.com/ponoor/step-series-support/discussions/6
