### ISSUE TITLE
opening a connection failed

### ISSUE THREAD

**Issue by kanta** [ponoor/python-step-series#4]
@JulianOrteil Hello Julien, thank you for your great work!
I am a super beginner of Python but trying to get started the library.
When I tried to run the "[First-steps example](https://github.com/ponoor/python-step-series#first-steps-example)" in README, I got this response from Python.
```
Traceback (most recent call last):
  File "C:\*\python-step-series\simpleTest.py", line 40, in <module>
    version: Version = device.get(GetVersion())
  File "c:\*\python-step-series\python-step-series-git\src\stepseries\stepXXX.py", line 272, in get
    self._check_status()
  File "c:\*\python-step-series\python-step-series-git\src\stepseries\stepXXX.py", line 167, in _check_status
    raise ClientClosedError(
stepseries.exceptions.ClientClosedError: the connection to this client is closed. Send the command 'SetDestIP' to open the connection or check your configurations

[process exited with code 1]
```

If I removed the final line
```
 version: Version = device.get(GetVersion())
```
then no errors.

The Ethernet connection was established (checked with `ping`). TX and RX LEDs on STEP400 blinked when I execute the code so it seems `/setDestIp` was sent successfully and the response was sent back to the PC. 
Are there any conditions to start the communication?

Thanks!

**Comment by JulianOrteil** [comment]
Hey @kanta,

Nope, everything you did looks to have been correct! I was able to successfully reproduce this. The issue appears to be that there is no delay between ``device.set(SetDestIP())`` and ``device.get(GetVersion())``. This means, internally, the library isn't able to verify the connection before you send ``/getVersion`` which results in this error. Try adding a ``time.sleep(0.1)`` delay between these two commands and see if that helps. You'll have to write ``import time`` at the very top of the file as well and don't need to add that delay between any other commands.

I'll likely change the behavior of ``/setDestIp`` so that the library waits for a response before other commands can be sent.

Thanks for the report!

**Comment by kanta** [comment]
@JulianOrteil `time.sleep(0.1)` worked perfectly! Now I'm ready to get in the library. Thank you for your help!
My goal at the moment is to make the testing tool you made work in my environment. So far I got many errors when I start `tox`. Do I need to make the same kind of edit to the testing tool codes?

**Comment by JulianOrteil** [comment]
@kanta Can you share a text file with the errors you get? I'll take a look in the morning.

**Comment by kanta** [comment]
Thanks, here is the log. [test_output_log_220228.txt](https://github.com/ponoor/python-step-series/files/8151326/test_output_log_220228.txt)

`tox` seems to be running the test several times and the log is very long. So I couldn't go back to the beginning of it. But I think this log contains at least one test loop result.

**Comment by JulianOrteil** [comment]
I'll take a look in a little bit. Indeed, tox does run multiple times. It is running the library against multiple versions of python (3.7-3.10) to verify its compatibility.

**Comment by JulianOrteil** [comment]
@kanta Run a `git pull` and try it again. I failed to remove `add_it_to_args` from some of the tests. It should work now.

Please keep in mind that some tests may require your interaction. I'll make them more explicit right now..

**Comment by kanta** [comment]
@JulianOrteil Thank you very much  for the update, now all `add_it_to_args` are gone!
The attached file is the output of the console. This test was done with both STEP400 (`10.0.0.100`) and STEP800 (`10.0.0.101`) connected.
[test_output_log_220301.txt](https://github.com/ponoor/python-step-series/files/8161502/test_output_log_220301.txt)

When I try to run tox, I get `UnicodeDecodeError` (as you can find it at the beginning of the log) quite often. But sometimes I can start the command, and can not find any regularity so far. This seems a problem of my environment and I will work for the error first then come back to the test codes.

**Comment by JulianOrteil** [comment]
@kanta Please run another `git pull`. I fixed a DNS query issue as seen at the end of your test log. Make sure to set `TestPresets.my_ip` in `conftest.py` for the STEP400 and STEP800 tests.

As for the `UnicodeDecodeError`, that appears to be an issue with tox and your environment as you've noted. Those are typically difficult to track down because the error message is virtually useless lol

I also labeled a couple more tests I missed as possibly requiring your interaction. If any test has the following syntax and you've set `TestPresets.homesw_exists` or `TestPresets.limitsw_exists` to True you will need to be prepared to press either switch: `test_<unique-name>_ui` (emphasis on the `ui` portion).

I would recommend running `pip install -U tox` and see if that helps?

**Comment by kanta** [comment]
@JulianOrteil Thanks for the updates! Still struggle with `UnicodeDecodeError` but I managed to start the test a couple of times.
[test_output_log_220302.txt](https://github.com/ponoor/python-step-series/files/8166301/test_output_log_220302.txt)

 
The current preset is;
```
    my_ip: str = "10.0.0.61"

    # Device networking settings
    id: int = 0
    address: str = "10.0.0.100"
    port: int = 50000
    server_address: str = "0.0.0.0"
    server_port: int = 50100
``` 
There are two network adaptors for my PC. One is `10.0.0.61` which is connected with STEP series, and other one is `192.168.1.22` for the internet connection. If I set `my_ip` as `192.168.1.22`, it cause the same error as the last time.

In the last time, I changed `server_address` as  `10.0.0.61`, but now I realize I can leave it as `0.0.0.0`. I'm not sure but probably this was the reason of the error?

Some other thoughts;
- The hardware was detected only in Python 3.10
- I set `enable_motors`, `homesw_exists` and `embrake_exists` as `True` for both STEP400 and 800 but the tests were skipped.

The Unicode error doesn't allow me to examine more but I will try to!

**Comment by JulianOrteil** [comment]
@kanta Thanks for your patience. That is pretty wierd on how only Python 3.10 was detecting the hardware. Baffling.

Can you share your entire `TestPresets` classes for both the 400 and 800? I wonder if there is some clashing configuration I'm not aware of.

Also, how you have your config set in the snippet you provided is correct. `server_address` should always be zeros and `my_ip` should be set to the ip address the controller is connecting to. Perhaps disabling your other adapter might help?

Jules

**Comment by kanta** [comment]
@JulianOrteil Sure, here are the class of both.
[TestPresets_STEP400.txt](https://github.com/ponoor/python-step-series/files/8167041/TestPresets_STEP400.txt)
[TestPresets_STEP800.txt](https://github.com/ponoor/python-step-series/files/8167042/TestPresets_STEP800.txt)

And thank you for checking the network configs. The error was successfully solved with your updated code even with 2 networks, but just wanted to tell the background (my mistake of `server _address`).

Anyway thank you again for your big help!!

**Comment by JulianOrteil** [comment]
@kanta Looking at your presets, you didn't set ``is_configured`` to true. This setting acts as an "Are you sure your settings are correct?" check before running certain tests that require hardware interaction (running motors, listening for switch presses, etc). It's curious that Python 3.10 ran with that set to False, but not any other versions. I can't reproduce this on my end.

```python
class TestPresets:
    # After configuring your settings below, set this to True
    is_configured: bool = False
```
should be
```python
class TestPresets:
    # After configuring your settings below, set this to True
    is_configured: bool = True
```

**Comment by JulianOrteil** [comment]
@kanta Please run another `git pull`. I just updated the tests to include more descriptions for `is_configured` :)

**Comment by kanta** [comment]
@JulianOrteil Thanks for pointing it out, now motor tests are physically running!!
[console_output_211209.txt](https://github.com/ponoor/python-step-series/files/8174019/console_output_211209.txt)

Still only works with Python 3.10, but if this is my environment depended, I will just use version 3.10 so no problem to execute the test. So I'm ready to work (still need to flight with Unicode error though), thank you!

Let me ask one more thing. I found I can edit `envlist` in `tox.ini` for using Python 3.10. But is there any way to execute the test individually for STEP400 and 800?

Thank you again for your help!

**Comment by JulianOrteil** [comment]
@kanta Great to hear it!

I noticed a couple of things from your output as well:
1) You're running this in what appears to be a PowerShell prompt. I've had multiple issues with PowerShell and Python, so try running these in a CMD prompt. This may be why Python 3.7-3.9 are failing while 3.10 is working with seemingly no explanation.
2) A file `tests/step400/test_actions.py` appears to be running and failing. I remember having this file quite a while ago, but I no longer have it as a part of the `tests` directory. Did you add this file? If not, I would recommend removing it.

As for testing STEP400 and STEP800 separately, there isn't currently. I can look at adding this if you think it would be beneficial. Currently, I just disconnect which device I'm not testing and go from there.

**Comment by kanta** [comment]
Thanks for the info!
Yes, I used the app named `Anaconda Powershell Prompt (Miniconda3)`. There is an another app named `Anaconda Prompt (Miniconda3)`, but the Unicode error never allowed me to try the test... I will try it out when I solve that weird error.

I don't find a file `tests/step400/test_actions.py` but found some `test_actions.cpython-3xx-pytest-6.2.5.pyc` files in `tests/step400/__pycache__`. I will remove them.

No problem for separating STEP400/800, I wanted to know if I can make it with commenting out just one line. 

So I have successfully done the test and the result already taught me some bugs! 
Big thanks for your help and effort, I will close this issue.

**Comment by JulianOrteil** [comment]
@kanta Perfect. Glad everything is working now!

Please let me know if you need anything else :)
Jules
