### ISSUE TITLE
Install the library and start communication on Ubuntu

### ISSUE THREAD

**Issue by kanta** [ponoor/python-step-series#6]
@JulianOrteil One of STEP400 users @Takamatsu-Matrix is trying to use this library on Ubuntu on Jetson nano. He managed to install the library but couldn't start communication. This is the question I wanted to ask your idea, but I have one another question before it.
I am trying to reproduce the problem on Jetson nano but couldn't install the library.

In the terminal of Jetson nano, I did
- `sudo apt-get install python3-venv`
- `python3 -m venv python-step-series`
- `. python-step-series/bin/activate`

And all these worked fine. But `pip install python-step-series` returns this error;
```
Could not find a version that satisfies the requirement python-step-series (from versions: )
No matching distribution found for python-step-series
```

`python3 -m pip install python-step-series` caused the same result.
Another library, for example, `python-OSC` could install properly. 

I know this is not a library specific issue but if you have any ideas about typical pitfalls for beginners, please let me know.
Thank you for your assistance!

**Comment by JulianOrteil** [comment]
@kanta Can you run ``python3 -V`` and let me know what version of python you are running on your Jetson?

The library requires at least python 3.7, so that might be why you can't install it.

**Comment by JulianOrteil** [comment]
As for the user, do you have the code they are using to communicate with the controller?

**Comment by kanta** [comment]
@JulianOrteil I see, your should be correct, because it was 3.6.9. Such a basic thing... I will try again with the proper version tomorrow, thanks!!

The code was following;
```
from stepseries.commands import GetVersion, SetDestIP
from stepseries.step400 import STEP400
from stepseries.responses import OSCResponse, Version
import time

def default_handler(message: OSCResponse) -> None:
    print("Message received:", message)

def version_handler(message: Version) -> None:
    print("Firmware:")
    print(" - Name:", message.firmware_name)
    print(" - Version:", message.firmware_version)
    print(" - Compiled:", message.compile_date)

if __name__ == '__main__':
    # Configurations that should be changed
    dip_switch_id = 1  # Should match what is set on the device
    local_ip_address = "10.0.0.101"  # The ip address of the device
    local_port = 50000
    server_address = "0.0.0.0"  # The address of the server; should always be 0.0.0.0 (the local machine)
    server_port = 50101

    # Create a device instance using the configurations above
    # This does two things: creates a communication interface and starts up an OSC endpoint for
    # the device to communicate with
    device = STEP400(dip_switch_id, local_ip_address, local_port, server_address, server_port)

    # Register a default handler for messages
    # Typically, these are used to log events and print to stdout
    # It is recommended to instead register 'filtered' handlers if
    # you want to parse the message (like the one below)
    device.on(None, default_handler)
    #print(default_handler)
    # Register a handler just for version info
    device.on(Version, version_handler)

    # Enable communication with the device
    device.set(SetDestIP())
    time.sleep(0.1)
    # Get the current version of the firmware
    version: Version = device.get(GetVersion())
   ```
This code works in my environment on Windows/Miniconda. 
And in the user side, this photo was the result.  
![0](https://user-images.githubusercontent.com/1097902/175944556-82abc40c-198d-4ab7-a304-8aad17e6bc41.jpg)
 
In his environment, `ping` works between the Jetson nano and the STEP400. He has made it to communicate with NODE-RED so the network should be okay. He said `python-OSC` worked as well.

I will try to reproduce the error tomorrow if I make it to install the library to a Jetson nano, and will come back with more detailed log.

**Comment by JulianOrteil** [comment]
@kanta Aye, the wrong Python version would do it.

As for the user's code, I don't see anything wrong with it. Perhaps he needs to increase ``time.sleep``? This can be something I address this week in a patch if this is the case.

**Comment by Takamatsu-Matrix** [comment]
I tried to increase time.sleep.
but it was same error.



![20220628_103449s](https://user-images.githubusercontent.com/107995386/176068665-36e452ed-0e4d-4279-b27d-731db6f64193.jpg)

**Comment by kanta** [comment]
@JulianOrteil As you guessed, the newer python version (3.9.14) solved all installing problems. Thanks!!
Then I successfully reproduced the same error as @Takamatsu-Matrix got. 
I executed a test code with python-OSC for the check;
```
from http import server
import time
from pythonosc import udp_client
from pythonosc import dispatcher
from pythonosc import osc_server

if __name__ == '__main__':
    dispatcher = dispatcher.Dispatcher()
    dispatcher.map("/destIp", print)
    server = osc_server.ThreadingOSCUDPServer(("0.0.0.0",50101), dispatcher)

    client = udp_client.SimpleUDPClient("10.0.0.101", 50000)
    client.send_message("/setDestIp", 0)
    server.serve_forever()
```

And I got the response properly.
```
/destIp 10 0 0 65 1
```
So the network setting should be fine.
With the packet capture (`tcpdump`), some UDP bytes were sent & received. With `python-step-series` code, nothings was sent (and received) so the problem will be a transmitting part.

I will continue to figure the problem out but let me know if you get any idea!

**Comment by JulianOrteil** [comment]
> I tried to increase time.sleep.
> but it was same error.
> 
> 
> 
> ![20220628_103449s](https://user-images.githubusercontent.com/107995386/176068665-36e452ed-0e4d-4279-b27d-731db6f64193.jpg)
> 

@Takamatsu-Matrix Curious! I will look into this. In the meantime, can you install the library through the source code from the ``documentation`` branch?

Just clone this repository somewhere to your machine, path into the repository, run ``git checkout documentation``, and then run ``python3 -m pip install -e .``. Make sure you have your virtual environment activated before running that last command.

**Comment by JulianOrteil** [comment]
@kanta I was not able to reproduce this on my end using my normal computer running Ubuntu linux. Can you try again using the ``documentation`` branch of this repo?

**Comment by kanta** [comment]
@JulianOrteil Excellent, you hit the nail! I set it up as you said and it worked!! Thank you very much for your support.

@Takamatsu-Matrix 
Here are what I did in my environment. / 私の環境で行った操作は以下の通りです。

1. Install Python3.9
2. Create the virtual environment
`python3.9 -m venv testenv-pss`
3. `git clone https://github.com/ponoor/python-step-series.git`
4. `export PATH="$PATH:home/nano/Desktop/step-series"`
5. `cd python-step-series`
6. `git checkout documentation`
7. `cd ..`
8. `. testenv-pss/bin/activate`
9. `python3 -m pip install -e .`
10. Now ready to execute the code. I got these texts in the console.
```
(testenv-pss) nano@ubuntu:~/Desktop/step-series$ python3.9 simpleTest.py
Message received: DestIP(address='/destIp', destIp0=10, destIp1=0, destIp2=0, destIp3=65, isNewDestIp=1)
Message received: Version(address='/version', firmware_name='STEP400_R1_UNIVERSAL', firmware_version='1.2.0', compile_date='Jun 10 2022 10:04:58')
Firmware:
 - Name: STEP400_R1_UNIVERSAL
 - Version: 1.2.0
 - Compiled: Jun 10 2022 10:04:58
 ```

**Comment by kanta** [comment]
@JulianOrteil I have just gotten the message from @Takamatsu-Matrix and he made it to execute the code with no errors. Thank you for your support! I would close this issue.
